-- Script was generated by Devart dbForge Studio for MySQL, Version 6.0.151.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 2013-04-28 18:58:20
-- Server version: 5.5.24-log
-- Client version: 4.1

SET NAMES 'utf8';
INSERT INTO adventuregame.rumkoppling(id, id_Rum1, id_Rum2, namn) VALUES
(1, 1, 2, 'Följ stigen in i skogen');
INSERT INTO adventuregame.rumkoppling(id, id_Rum1, id_Rum2, namn) VALUES
(2, 2, 1, 'Gå ut i gläntan');
INSERT INTO adventuregame.rumkoppling(id, id_Rum1, id_Rum2, namn) VALUES
(3, 2, 3, 'Fortsätt stigen fram');
INSERT INTO adventuregame.rumkoppling(id, id_Rum1, id_Rum2, namn) VALUES
(4, 3, 4, 'Gå in i grottan');
INSERT INTO adventuregame.rumkoppling(id, id_Rum1, id_Rum2, namn) VALUES
(5, 4, 3, 'Grottöppningen');
INSERT INTO adventuregame.rumkoppling(id, id_Rum1, id_Rum2, namn) VALUES
(6, 3, 2, 'Följ stigen in i skogen');
INSERT INTO adventuregame.rumkoppling(id, id_Rum1, id_Rum2, namn) VALUES
(7, 4, 5, 'Mitt i skogen');
INSERT INTO adventuregame.rumkoppling(id, id_Rum1, id_Rum2, namn) VALUES
(8, 1, 7, 'Stig utmed bäck');
INSERT INTO adventuregame.rumkoppling(id, id_Rum1, id_Rum2, namn) VALUES
(9, 7, 1, 'Gå  ut i gläntan');
INSERT INTO adventuregame.rumkoppling(id, id_Rum1, id_Rum2, namn) VALUES
(10, 7, 8, 'Bro över bäcken');
INSERT INTO adventuregame.rumkoppling(id, id_Rum1, id_Rum2, namn) VALUES
(11, 8, 7, 'Stig utmed bäck');
INSERT INTO adventuregame.rumkoppling(id, id_Rum1, id_Rum2, namn) VALUES
(12, 8, 9, 'Brygga vid bäcken');
INSERT INTO adventuregame.rumkoppling(id, id_Rum1, id_Rum2, namn) VALUES
(13, 9, 8, 'Bro över bäcken');
INSERT INTO adventuregame.rumkoppling(id, id_Rum1, id_Rum2, namn) VALUES
(14, 9, 6, 'Djupa skogen');
INSERT INTO adventuregame.rumkoppling(id, id_Rum1, id_Rum2, namn) VALUES
(15, 6, 10, 'Offerplats');
INSERT INTO adventuregame.rumkoppling(id, id_Rum1, id_Rum2, namn) VALUES
(16, 6, 5, 'Mitt i skogen');
INSERT INTO adventuregame.rumkoppling(id, id_Rum1, id_Rum2, namn) VALUES
(17, 10, 6, 'Djupa skogen');
INSERT INTO adventuregame.rumkoppling(id, id_Rum1, id_Rum2, namn) VALUES
(18, 5, 1, 'Skogsgläntan');
INSERT INTO adventuregame.rumkoppling(id, id_Rum1, id_Rum2, namn) VALUES
(19, 5, 4, 'Gå in i grottan');
