-- Script was generated by Devart dbForge Studio for MySQL, Version 6.0.151.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 2013-04-28 18:58:20
-- Server version: 5.5.24-log
-- Client version: 4.1

SET NAMES 'utf8';
INSERT INTO adventuregame.rum(id, namn, beskrivning, grafik) VALUES
(1, 'Stranden', 'Du är strandsatt på en ö för ett komma hem måste du hitta nyckeln till skeppet som ska ta dig hem.', '<embed type="image/svg+xml" src="img/skogsglanta.svg" width="707" height="480" />');
INSERT INTO adventuregame.rum(id, namn, beskrivning, grafik) VALUES
(2, 'Stig i skogen', 'Du vandrar på en stig inne i skogen. Fåglarna kvittrar och solen skiner. Du är på topphumör. Stigen fortsätter djupare in i skogen. Åt andra hållet ser du en skogslänta där skogen tar slut.', '<embed type="image/svg+xml" src="img/stigskog.svg" width="707" height="480" />');
INSERT INTO adventuregame.rum(id, namn, beskrivning, grafik) VALUES
(3, 'Grottöppning', 'Du kommer till en liten öppning och befinner dig mitt framför en grottöppning. Det ser mörkt och kallt ut i grottan, men ändå lite spännande. Stigen går in i skogen åt andra hållet.', '<embed type="image/svg+xml" src="img/utgrotta.svg" width="707" height="480" />');
INSERT INTO adventuregame.rum(id, namn, beskrivning, grafik) VALUES
(4, 'Grotta', 'Du är mitt i den djupa grottan. Du är förstummad över dess skönhet. Du sitter ned och betraktar dess former som växt fram under årtusenden. Lite längre bort ser du 2 röda ungdomar som försvinner in i en av gångarna. Ett svagt ljussken lyser in bakom dig. Det finns väldigt många vägar att välja på.', '<embed type="image/svg+xml" src="img/cave.svg" width="707" height="480" />');
INSERT INTO adventuregame.rum(id, namn, beskrivning, grafik) VALUES
(5, 'Mitt i skogen', 'Du är mitt i skogen, det är svårt att se skogen för alla träden är i vägen. Vart skall du ta vägen? Fundera, fundera, fundera...', '<embed type="image/svg+xml" src="img/mitt_i_skogen.svg" width="720" height="480" />');
INSERT INTO adventuregame.rum(id, namn, beskrivning, grafik) VALUES
(6, 'Djupa skogen', 'Du är mitt i skogen och ser lite vilsen ut. Det ser nästan ut som om det börjar mörkna, men kanske är det bara ett moln... Du ser dig om och funderar åt vilket håll som du bör fortsätta... Nu gäller det...', '<embed type="image/svg+xml" src="img/djupa_skogen.svg" width="720" height="480" />');
INSERT INTO adventuregame.rum(id, namn, beskrivning, grafik) VALUES
(7, 'Stig utmed bäck', 'Solen står högt på himlen och du vandrar på stigen längs den porlande bäcken. Du funderar på om Näcken bor i en sådan här bäck. Du har alltid funderat på hur det vore att möta Näcken. Till vänster ser du en bro. Till höger om dig är en skogsglänta.', '<embed type="image/svg+xml" src="img/langsbacken.svg" width="720" height="480" />');
INSERT INTO adventuregame.rum(id, namn, beskrivning, grafik) VALUES
(8, 'Bro över bäcken', 'Du har kommit till en bro som går över bäcken. Den ser lite ranglig ut men det håller säkert.', '<embed type="image/svg+xml" src="img/bro.svg" width="720" height="480" />');
INSERT INTO adventuregame.rum(id, namn, beskrivning, grafik) VALUES
(9, 'Brygga vid bäcken', 'Du vandrar längs bäcken och ser en brygga med en båt fastbunden. Båten ser lite ranglig ut men du gissar att den håller för dig. Längre bort till höger ser du en bro.', '<embed type="image/svg+xml" src="img/brygga.svg" width="720" height="480" />');
INSERT INTO adventuregame.rum(id, namn, beskrivning, grafik) VALUES
(10, 'Skogen offerplats', 'Du står i en glänta mitt framför en historisk och magisk offerplats. Den här platsen verkar spännande. Det kan nog vara denna plats som du letat efter så länge. Se dig omkring. Du ser en kortlek.', '<embed type="image/svg+xml" src="img/offerplats.svg" width="720" height="480" />');
